export const PENGADUAN_CREATE_REQUEST = "PENGADUAN_CREATE_REQUEST";
export const PENGADUAN_CREATE_SUCCESS = "PENGADUAN_CREATE_SUCCESS";
export const PENGADUAN_CREATE_FAIL = "PENGADUAN_CREATE_FAIL";
export const PENGADUAN_CREATE_RESET = "PENGADUAN_CREATE_RESET";

export const PENGADUAN_LIST_USER_REQUEST = "PENGADUAN_LIST_REQUEST";
export const PENGADUAN_LIST_USER_SUCCESS = "PENGADUAN_LIST_SUCCESS";
export const PENGADUAN_LIST_USER_FAIL = "PENGADUAN_LIST_FAIL";
export const PENGADUAN_LIST_USER_RESET = "PENGADUAN_LIST_RESET";

export const PENGADUAN_DELETE_REQUEST = "PENGADUAN_DELETE_REQUEST";
export const PENGADUAN_DELETE_SUCCESS = "PENGADUAN_DELETE_SUCCESS";
export const PENGADUAN_DELETE_FAIL = "PENGADUAN_DELETE_FAIL";
