export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";
export const ADMIN_LOGOUT = "ADMIN_LOGOUT";

export const ADMIN_DETAILS_REQUEST = "ADMIN_DETAILS_REQUEST";
export const ADMIN_DETAILS_SUCCESS = "ADMIN_DETAILS_SUCCESS";
export const ADMIN_DETAILS_FAIL = "ADMIN_DETAILS_FAIL";
export const ADMIN_DETAILS_RESET = "ADMIN_DETAILS_RESET";

export const ADMIN_REGISTER_REQUEST = "ADMIN_REGISTER_REQUEST";
export const ADMIN_REGISTER_SUCCESS = "ADMIN_REGISTER_SUCCESS";
export const ADMIN_REGISTER_FAIL = "ADMIN_REGISTER_FAIL";

export const ADMIN_UPDATE_PROFILE_REQUEST = "ADMIN_UPDATE_PROFILE_REQUEST";
export const ADMIN_UPDATE_PROFILE_SUCCESS = "ADMIN_UPDATE_PROFILE_SUCCESS";
export const ADMIN_UPDATE_PROFILE_FAIL = "ADMIN_UPDATE_PROFILE_FAIL";
export const ADMIN_UPDATE_PROFILE_RESET = "ADMIN_UPDATE_PROFILE_RESET";

export const ADMIN_LIST_REQUEST = "ADMIN_LIST_REQUEST";
export const ADMIN_LIST_SUCCESS = "ADMIN_LIST_SUCCESS";
export const ADMIN_LIST_FAIL = "ADMIN_LIST_FAIL";
export const ADMIN_LIST_RESET = "ADMIN_LIST_RESET";

export const ADMIN_DELETE_REQUEST = "ADMIN_DELETE_REQUEST";
export const ADMIN_DELETE_SUCCESS = "ADMIN_DELETE_SUCCESS";
export const ADMIN_DELETE_FAIL = "ADMIN_DELETE_FAIL";

export const ADMIN_UPDATE_LEVEL_REQUEST = "ADMIN_UPDATE_LEVEL_REQUEST";
export const ADMIN_UPDATE_LEVEL_SUCCESS = "ADMIN_UPDATE_LEVEL_SUCCESS";
export const ADMIN_UPDATE_LEVEL_FAIL = "ADMIN_UPDATE_LEVEL_FAIL";
export const ADMIN_UPDATE_LEVEL_RESET = "ADMIN_UPDATE_LEVEL_RESET";
