export const TANGGAPAN_LIST_REQUEST = "TANGGAPAN_LIST_REQUEST";
export const TANGGAPAN_LIST_SUCCESS = "TANGGAPAN_LIST_SUCCESS";
export const TANGGAPAN_LIST_FAIL = "TANGGAPAN_LIST_FAIL";
export const TANGGAPAN_LIST_RESET = "TANGGAPAN_LIST_RESET";

export const TANGGAPAN_DELETE_REQUEST = "TANGGAPAN_DELETE_REQUEST";
export const TANGGAPAN_DELETE_SUCCESS = "TANGGAPAN_DELETE_SUCCESS";
export const TANGGAPAN_DELETE_FAIL = "TANGGAPAN_DELETE_FAIL";

export const TANGGAPAN_DETAILS_REQUEST = "TANGGAPAN_DETAILS_REQUEST";
export const TANGGAPAN_DETAILS_SUCCESS = "TANGGAPAN_DETAILS_SUCCESS";
export const TANGGAPAN_DETAILS_FAIL = "TANGGAPAN_DETAILS_FAIL";
export const TANGGAPAN_DETAILS_RESET = "TANGGAPAN_DETAILS_RESET";

export const TANGGAPAN_ADD_REQUEST = "TANGGAPAN_ADD_REQUEST";
export const TANGGAPAN_ADD_SUCCESS = "TANGGAPAN_ADD_SUCCESS";
export const TANGGAPAN_ADD_FAIL = "TANGGAPAN_ADD_FAIL";
export const TANGGAPAN_ADD_RESET = "TANGGAPAN_ADD_RESET";

export const TANGGAPAN_STATUS_REQUEST = "TANGGAPAN_STATUS_REQUEST";
export const TANGGAPAN_STATUS_SUCCESS = "TANGGAPAN_STATUS_SUCCESS";
export const TANGGAPAN_STATUS_FAIL = "TANGGAPAN_STATUS_FAIL";
export const TANGGAPAN_STATUS_RESET = "TANGGAPAN_STATUS_RESET";

export const TANGGAPAN_LIST_USER_REQUEST = "TANGGAPAN_LIST_REQUEST";
export const TANGGAPAN_LIST_USER_SUCCESS = "TANGGAPAN_LIST_SUCCESS";
export const TANGGAPAN_LIST_USER_FAIL = "TANGGAPAN_LIST_FAIL";
export const TANGGAPAN_LIST_USER_RESET = "TANGGAPAN_LIST_RESET";
